openapi: 3.0.3
info:
  title: Drawing API Contract
  description: API contract for supervision library integration in vehicle detection visualization
  version: 1.0.0
  contact:
    name: ONNX Vehicle Detection Team

paths:
  /draw_detections:
    post:
      summary: Draw detection results on image
      description: |
        Main function to draw detection bounding boxes and OCR results on an image.
        Supports both supervision and PIL backend with automatic fallback.
      operationId: draw_detections
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DrawDetectionsRequest'
      responses:
        '200':
          description: Successfully drew detections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DrawDetectionsResponse'
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal drawing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /convert_detections:
    post:
      summary: Convert detection format
      description: Convert legacy tuple format to supervision.Detections format
      operationId: convert_to_supervision_detections
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertDetectionsRequest'
      responses:
        '200':
          description: Successfully converted detections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertDetectionsResponse'

  /benchmark:
    post:
      summary: Performance benchmark
      description: Compare performance between PIL and supervision backends
      operationId: benchmark_drawing_performance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BenchmarkRequest'
      responses:
        '200':
          description: Benchmark completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BenchmarkResponse'

components:
  schemas:
    # Input Schemas
    DrawDetectionsRequest:
      type: object
      required:
        - image_shape
        - detections
        - class_names
        - colors
      properties:
        image_shape:
          $ref: '#/components/schemas/ImageShape'
        detections:
          $ref: '#/components/schemas/DetectionBatch'
        class_names:
          type: array
          items:
            type: string
          example: ["vehicle", "plate"]
        colors:
          type: array
          items:
            $ref: '#/components/schemas/Color'
        plate_results:
          type: array
          items:
            $ref: '#/components/schemas/PlateOCRResult'
          nullable: true
        font_path:
          type: string
          default: "SourceHanSans-VF.ttf"
          description: Path to Chinese font file
        use_supervision:
          type: boolean
          default: true
          description: Whether to use supervision backend

    ConvertDetectionsRequest:
      type: object
      required:
        - detections
        - class_names
      properties:
        detections:
          $ref: '#/components/schemas/DetectionBatch'
        class_names:
          type: array
          items:
            type: string

    BenchmarkRequest:
      type: object
      required:
        - image_shape
        - detections
        - class_names
        - colors
      properties:
        image_shape:
          $ref: '#/components/schemas/ImageShape'
        detections:
          $ref: '#/components/schemas/DetectionBatch'
        class_names:
          type: array
          items:
            type: string
        colors:
          type: array
          items:
            $ref: '#/components/schemas/Color'
        iterations:
          type: integer
          default: 100
          minimum: 1
          maximum: 1000

    # Response Schemas
    DrawDetectionsResponse:
      type: object
      required:
        - success
        - backend_used
        - performance_metrics
      properties:
        success:
          type: boolean
        backend_used:
          type: string
          enum: ["supervision", "pil"]
        performance_metrics:
          $ref: '#/components/schemas/PerformanceMetrics'
        errors:
          type: array
          items:
            type: string
        warnings:
          type: array
          items:
            type: string
        image_shape:
          $ref: '#/components/schemas/ImageShape'

    ConvertDetectionsResponse:
      type: object
      required:
        - success
        - detection_count
      properties:
        success:
          type: boolean
        detection_count:
          type: integer
          minimum: 0
        supervision_format:
          $ref: '#/components/schemas/SupervisionDetections'
        errors:
          type: array
          items:
            type: string

    BenchmarkResponse:
      type: object
      required:
        - success
        - pil_metrics
        - supervision_metrics
        - improvement_ratio
      properties:
        success:
          type: boolean
        pil_metrics:
          $ref: '#/components/schemas/PerformanceMetrics'
        supervision_metrics:
          $ref: '#/components/schemas/PerformanceMetrics'
        improvement_ratio:
          type: number
          format: float
          minimum: 0
        test_timestamp:
          type: string
          format: date-time

    # Data Models
    ImageShape:
      type: object
      required:
        - height
        - width
        - channels
      properties:
        height:
          type: integer
          minimum: 1
          maximum: 8192
        width:
          type: integer
          minimum: 1
          maximum: 8192
        channels:
          type: integer
          enum: [3]  # Only BGR format supported

    DetectionTuple:
      type: array
      items:
        type: number
      minItems: 6
      maxItems: 6
      description: "[x1, y1, x2, y2, confidence, class_id]"
      example: [100, 150, 300, 400, 0.95, 0]

    DetectionBatch:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/DetectionTuple'
      description: "Batch of detections: [[detection1, detection2, ...]]"

    SupervisionDetections:
      type: object
      required:
        - xyxy
        - confidence
        - class_id
      properties:
        xyxy:
          type: array
          items:
            type: array
            items:
              type: number
            minItems: 4
            maxItems: 4
          description: "Bounding box coordinates [[x1,y1,x2,y2], ...]"
        confidence:
          type: array
          items:
            type: number
            minimum: 0.0
            maximum: 1.0
          description: "Confidence scores [conf1, conf2, ...]"
        class_id:
          type: array
          items:
            type: integer
            minimum: 0
          description: "Class IDs [cls1, cls2, ...]"
        data:
          type: object
          additionalProperties: true
          description: "Additional metadata"

    PlateOCRResult:
      type: object
      required:
        - plate_text
        - color
        - layer
        - confidence
        - should_display_ocr
      properties:
        plate_text:
          type: string
          pattern: '^[A-Z0-9\u4e00-\u9fff]+$'
          minLength: 6
          maxLength: 8
          description: "License plate text"
        color:
          type: string
          enum: ["蓝牌", "绿牌", "黄牌", "白牌", "黑牌", "unknown"]
          description: "License plate color"
        layer:
          type: string
          enum: ["单层", "双层", "unknown"]
          description: "License plate layer type"
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: "OCR confidence score"
        should_display_ocr:
          type: boolean
          description: "Whether to display OCR results"
        text_position:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
          nullable: true
          description: "Text position [x, y]"
        text_bbox:
          type: array
          items:
            type: integer
          minItems: 4
          maxItems: 4
          nullable: true
          description: "Text bounding box [x1, y1, x2, y2]"

    Color:
      type: object
      required:
        - r
        - g
        - b
      properties:
        r:
          type: integer
          minimum: 0
          maximum: 255
        g:
          type: integer
          minimum: 0
          maximum: 255
        b:
          type: integer
          minimum: 0
          maximum: 255
      example:
        r: 255
        g: 0
        b: 0

    PerformanceMetrics:
      type: object
      required:
        - draw_time_ms
        - detection_count
        - ocr_count
        - image_resolution
        - backend_used
      properties:
        draw_time_ms:
          type: number
          format: float
          minimum: 0
          description: "Drawing time in milliseconds"
        detection_count:
          type: integer
          minimum: 0
          description: "Number of detection objects"
        ocr_count:
          type: integer
          minimum: 0
          description: "Number of OCR objects"
        image_resolution:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
          description: "Image resolution [width, height]"
        backend_used:
          type: string
          enum: ["supervision", "pil"]
          description: "Backend used for drawing"
        objects_per_second:
          type: number
          format: float
          minimum: 0
          description: "Objects processed per second"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: "Error type"
        message:
          type: string
          description: "Error message"
        details:
          type: object
          additionalProperties: true
          description: "Additional error details"
        timestamp:
          type: string
          format: date-time

# API Contract Validation Rules
x-contract-validation:
  input_constraints:
    - "image_shape.height * image_shape.width <= 33177600"  # Max 8K resolution
    - "len(detections[0]) <= 100"  # Max 100 detections per image
    - "len(class_names) <= 50"     # Max 50 classes
    - "len(colors) >= len(class_names)"  # Enough colors for all classes

  performance_constraints:
    - "draw_time_ms <= 50.0"  # Max 50ms drawing time
    - "objects_per_second >= 200"  # Min 200 objects/second

  quality_constraints:
    - "supervision backend preferred for performance"
    - "PIL fallback required for compatibility"
    - "Chinese font support mandatory"

  compatibility_constraints:
    - "input format: legacy tuple detections"
    - "output format: BGR numpy array"
    - "API signature: preserve existing function signature"
